server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/application/**
    discovery:
      locator:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka