info:
  app:
    name: User Service
    description: This is the user management microservice
    version: 1.0.0

spring:
  config:
    import: configserver:http://localhost:8888

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/